# See https://github.com/weaveworks/weave-gitops/tree/main/charts/gitops-server
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      version: "4.x"
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  valuesFrom:
    - kind: Secret
      name: weave-gitops
  values:
    ingress:
      hosts:
        - host: flux.local
          paths:
            - path: /
              pathType: ImplementationSpecific
