apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: fastapi
  labels:
    app: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
      nodePort: 30080