# See https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      version: "4.7.x"
  # Compatibility with kind clusters
  # See https://github.com/kubernetes/ingress-nginx/blob/main/hack/manifest-templates/provider/kind/values.yaml
  values:
    controller:
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
      hostPort:
        enabled: true
      terminationGracePeriodSeconds: 0
      service:
        type: NodePort
      watchIngressWithoutClass: true
      # nodeSelector:
      #   ingress-ready: "true"
      #     tolerations:
      #       - key: "node-role.kubernetes.io/master"
      #         operator: "Equal"
      #         effect: "NoSchedule"
      #       - key: "node-role.kubernetes.io/control-plane"
      #         operator: "Equal"
      #         effect: "NoSchedule"
      publishService:
        enabled: false
      extraArgs:
        publish-status-address: localhost
