apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend
  namespace: default
spec:
  interval: 15m
  path: "./infra/apps/backend/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: backend