apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: app
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080