# This config applies recursively to all sub-directories.

# Multiple directories can use separate SOPS configs.

# Contributors using the sops CLI to create and encrypt files won’t have to worry
# about specifying the proper key for the target cluster or namespace.
# Therefore, they can just encrypt files with `sops -e file.yaml`

# Private key should be in ./cluster/{name}/sops.agekey

# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # Dev secrets
  - path_regex: .*dev/.*values-secret.yaml
    age: age1ln0hyfv26nu7c9ljq99aulgqxu3y2l3jggv9ggt9pekqvz8tu34q9a4zwt
  - path_regex: .*dev/.*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age1ln0hyfv26nu7c9ljq99aulgqxu3y2l3jggv9ggt9pekqvz8tu34q9a4zwt
  # Stage secrets
  - path_regex: .*stage/.*values-secret.yaml
    age: age13v4rf2q0mxzs9v0udqanppm6flg4nxwmmg69yhq0n5f57ka5mvhsu5l6qt
  - path_regex: .*stage/.*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age13v4rf2q0mxzs9v0udqanppm6flg4nxwmmg69yhq0n5f57ka5mvhsu5l6qt
  # Prod secrets
  - path_regex: .*prod/.*values-secret.yaml
    age: age1ed5rue36y4h3xewkf2rcatkge3936mdle2zpx6njyjrjeaelkglsy0c4z3
  - path_regex: .*prod/.*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age1ed5rue36y4h3xewkf2rcatkge3936mdle2zpx6njyjrjeaelkglsy0c4z3