kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6545
        hostPort: 6545
        listenAddress: "127.0.0.1"
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 8084
        protocol: TCP
      - containerPort: 443
        hostPort: 4434
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 8085
        protocol: TCP
      - containerPort: 443
        hostPort: 4435
        protocol: TCP
