apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fastapi
  namespace: default
spec:
  image: h2axsa4sandbox4acr.azurecr.io/hello-version-fastapi
  exclusionList:
    - 'latest'
  interval: 10s
  secretRef:
    name: acr-credentials
