apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
  namespace: default
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: h2axsa4sandbox4acr.azurecr.io/hello-version-flask:25 # {"$imagepolicy": "default:flask"}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-example # this will be replaced by Kustomize with the generated name of the ConfigMap
      imagePullSecrets:
      - name: acr-credentials
