apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
  namespace: default
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: hello-version-flask:0.0.1
        ports:
        - containerPort: 8080