apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: flask
  labels:
    app: flask
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080