apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  template:
    spec:
      containers:
        - name: fastapi
          resources:
            limits:
              cpu: "0.1"
              memory: "128Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"