apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
configMapGenerator:
  - name: env-example # it will replace the configmap that it founds with this name and add a hash
    behavior: merge
    literals:
      - ENV=prod
commonLabels:
  environment: prod
images:
  - name: h2axsa4sandbox4acr.azurecr.io/hello-version-fastapi
    newName: h2axsa4sandbox4acr.azurecr.io/hello-version-fastapi-prod # {"$imagepolicy": "default:fastapi:name"}
    newTag: "37" # {"$imagepolicy": "default:fastapi:tag"}
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: fastapi