name: Build and Push FastAPI image to ACR

on: 
  push:
    branches: ['main']
    paths: ['app/fastapi/src/**']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push
    environment: 'Production'
    steps:
      - uses: actions/checkout@v4
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR
        run: |
          az acr login -n ${{ vars.ACR_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:app/fastapi"
          push: true
          tags: |
            ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.ACR_REPO_FASTAPI }}:${{ github.run_number }}
            ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.ACR_REPO_FASTAPI }}:latest
      - name: Log out
        run: |
          az logout