apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/weave-gitops
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
# See https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: weave-gitops
    files:
      - values.yaml=values-secret.enc.yaml
configurations:
  - kustomizeconfig.yaml
